// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACu5dvbeH6OARZq0hdKSrl_Tt1UsWSwWo',
    appId: '1:130229530955:web:44ab342777f6dcf5b0b8ce',
    messagingSenderId: '130229530955',
    projectId: 'blue-light-7248e',
    authDomain: 'blue-light-7248e.firebaseapp.com',
    storageBucket: 'blue-light-7248e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtkioXRtqlENAShwMo5C0AKGDYvKIpDNM',
    appId: '1:130229530955:android:72fad8d309ab7d16b0b8ce',
    messagingSenderId: '130229530955',
    projectId: 'blue-light-7248e',
    storageBucket: 'blue-light-7248e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KZK4lCAEIFW6Op2Cs7GaQnRlvitEEVM',
    appId: '1:130229530955:ios:a3e6b626314bdfa5b0b8ce',
    messagingSenderId: '130229530955',
    projectId: 'blue-light-7248e',
    storageBucket: 'blue-light-7248e.firebasestorage.app',
    iosBundleId: 'com.example.blueLight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KZK4lCAEIFW6Op2Cs7GaQnRlvitEEVM',
    appId: '1:130229530955:ios:a3e6b626314bdfa5b0b8ce',
    messagingSenderId: '130229530955',
    projectId: 'blue-light-7248e',
    storageBucket: 'blue-light-7248e.firebasestorage.app',
    iosBundleId: 'com.example.blueLight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACu5dvbeH6OARZq0hdKSrl_Tt1UsWSwWo',
    appId: '1:130229530955:web:9ae1073c0b689c80b0b8ce',
    messagingSenderId: '130229530955',
    projectId: 'blue-light-7248e',
    authDomain: 'blue-light-7248e.firebaseapp.com',
    storageBucket: 'blue-light-7248e.firebasestorage.app',
  );

}